---
layout: post
num: 1
title: Exercise 1
chapter: Chapter 12
description: >
  (2) Create a class with a main( ) that throws an object of class Exception inside a try block. Give the constructor for Exception a String argument. Catch the exception inside a catch clause and print the String argument. Add a finally clause and print a message to prove you were there.
---



```java


package com.ciaoshen.thinkinjava.chapter12;

public class Exercise1 {
    public static void main(String[] args) {
        try {
            String msg = "This is Exercise 1 of chapter 12!";
            throw new Exception(msg);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            System.out.println("In finally block of chapter 12 - exercise 1");
        }
    }
}


```



